apiVersion: v1
kind: Service
metadata:
   name: olt
   namespace: voltha
   labels:
     name: olt
spec:
  ports:
    - name: grpc
      port: 50060
      targetPort: 50060
  selector:
    app: olt
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: olt
  namespace: voltha
spec:
   replicas: 1
   template:
     metadata:
       labels:
         app: olt
       annotations:
         cni: "weave"
     spec:
       containers:
         - name: olt
           image: "voltha-ponsim:latest"
           env:
             - name: POD_IP
               valueFrom:
                 fieldRef:
                   fieldPath: status.podIP
             - name: NAMESPACE
               valueFrom:
                 fieldRef:
                   fieldPath: metadata.namespace

           args:
             - "/app/ponsim"
             - "-device_type"
             - "OLT"
             - "-onus"
             - "3"
             - "-internal_if"
             - "eth0"
             - "-external_if"
             - "eth0"
             - "-vcore_endpoint"
             - "vcore"
             - "-promiscuous"
             - "-fluentd"
             - "fluentd.$(NAMESPACE).svc.cluster.local:24224"

           ports:
            - containerPort: 50060
              name: grpc-port

           imagePullPolicy: Never
