# Copyright 2017-present Open Networking Foundation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
apiVersion: v1
kind: Service
metadata:
   name: olt
   namespace: voltha
   labels:
     name: olt
spec:
  ports:
    - name: grpc
      port: 50060
      targetPort: 50060
  selector:
    app: olt
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: olt
  namespace: voltha
spec:
   replicas: 1
   template:
     metadata:
       labels:
         app: olt
       annotations:
         cni: "calico"
     spec:
       containers:
         - name: olt
           image: "voltha-ponsim:latest"
           env:
             - name: POD_IP
               valueFrom:
                 fieldRef:
                   fieldPath: status.podIP
             - name: NAMESPACE
               valueFrom:
                 fieldRef:
                   fieldPath: metadata.namespace

           args:
             - "/app/ponsim"
             - "-device_type"
             - "OLT"
             - "-onus"
             - "4"
             - "-internal_if"
             - "eth0"
             - "-external_if"
             - "eth0"
             - "-vcore_endpoint"
             - "vcore"
             - "-promiscuous"
             - "-fluentd"
             - "fluentd.$(NAMESPACE).svc.cluster.local:24224"

           ports:
            - containerPort: 50060
              name: grpc-port

           imagePullPolicy: Never
