apiVersion: v1
kind: Service
metadata:
   name: onos
   labels:
     name: onos
spec:
  ports:
    - name: ssh
      port: 8101
      targetPort: 8101
    - name: of
      port: 6653
      targetPort: 6653
    - name: ui
      port: 8181
      targetPort: 8181
  selector:
    app: onos
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: onos
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: onos
      annotations:
        cni: "weave"
    spec:
      containers:
        - name: onos
          image: "voltha-onos:latest"
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: ONOS_APPS
              value: "drivers,openflow-base"
          ports:
            - containerPort: 8101
              name: ssh-port
            - containerPort: 6653
              name: of-port
            - containerPort: 8181
              name: ui-port
          imagePullPolicy: Never
