apiVersion: v1
kind: Service
metadata:
   name: onu
   namespace: voltha
   labels:
     name: onu
spec:
  ports:
    - name: grpc
      port: 50061
      targetPort: 50061
  selector:
    app: onu
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: onu
  namespace: voltha
spec:
   replicas: 3
   template:
     metadata:
       labels:
         app: onu
       annotations:
         cni: "weave,pon0"
     spec:
       containers:
         - name: onu
           image: "voltha-ponsim:latest"
           env:
             - name: POD_IP
               valueFrom:
                 fieldRef:
                   fieldPath: status.podIP
             - name: NAMESPACE
               valueFrom:
                 fieldRef:
                   fieldPath: metadata.namespace

           args:
             - "/app/ponsim"
             - "-device_type"
             - "ONU"
             - "-parent_addr"
             - "olt"
             - "-grpc_port"
             - "50061"
             - "-internal_if"
             - "eth0"
             - "-external_if"
             - "eth1"
             - "-promiscuous"
             - "-fluentd"
             - "fluentd.$(NAMESPACE).svc.cluster.local:24224"

           ports:
            - containerPort: 50061
              name: grpc-port

           imagePullPolicy: Never
