version: '2'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.0
    environment:
      - transport.host=localhost
      - transport.tcp.port=9300
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
