#
# This stackfile deploys dashd and shovel services to a docker swarm.
#
# Each of these services depends on:
# - consul     (service)
# - kafka      (service)
# - grafana    (service)
# - voltha_net (overlay network)
#
# To deploy the stack, issue the command:
#
#     docker stack deploy -c docker-compose-stats-swarm.yml stats
#

version: "3"
services:
  dashd:
    image: cord/dashd
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: 3
    deploy:
      replicas: 1
    entrypoint:
      - /dashd/dashd/main.py
      - --kafka=kafka
      - --consul=consul:8500
      - --grafana_url=http://admin:admin@grafana:80/api
      - --topic=voltha.kpis
      - --docker_host=${DOCKER_HOST_IP}
    networks:
      - voltha-net

  shovel:
    image: cord/shovel
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: 3
    deploy:
      replicas: 1
    entrypoint:
      - /shovel/shovel/main.py
      - --kafka=kafka
      - --consul=consul:8500
      - --topic=voltha.kpis
      - --host=grafana
    networks:
      - voltha-net

networks:
  voltha-net:
    external:
      name: voltha_net

