#
# This Docker stackfile deploys a netconf swarm, one container per node.
#
# Netconf depends on the following being present:
# - the 'voltha_net' overlay network
# - the Voltha service
#
# To deploy the stack, issue the command:
#
#     docker stack deploy -c docker-compose-netconf-swarm.yml netconf
#

version: "3"
services:
  netconf:
    image: cord/netconf:latest
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: 3
    deploy:
      mode: global
    environment:
      SERVICE_1830_NAME: "netconf-server"
    entrypoint:
      - /netconf/netconf/main.py
      - -v
      - --consul=consul:8500
      - --fluentd=fluentd:24224
      - --grpc-endpoint=voltha:50555
      - --instance-id-is-container-name
    networks:
      - voltha-net
    ports:
      - "830:1830"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
      
networks:
  voltha-net:
    external:
      name: voltha_net

