version: '2'

services:

 freeradius:
  image: "${REGISTRY}tpdock/freeradius:latest"
  ports:
   - "1812:1812/udp"
   - "1813:1813"
   - "18120:18120"
  environment:
   RADIUS_LISTEN_IP: '*'
   USERS_FILE: '/etc/raddb/users'
   RADIUS_CLIENTS : 'SECRET@172.25.0.200'
  volumes:
   - "./data/users:/etc/raddb/users"
  networks:
   authnet:
    ipv4_address: 172.25.0.100


 onos:
  image: "${REGISTRY}${REPOSITORY}voltha-onos:latest"
  ports:
   - "8101:8101" # ssh
   - "6653:6653" # OF
   - "8181:8181" # UI
  environment:
   ONOS_APPS: 'drivers,openflow-base'
  networks:
    authnet:
     ipv4_address: 172.25.0.200

# onos_config_push:
#  image: "${REGISTRY}${REPOSITORY}voltha-config-push:${TAG:-latest}"
#  environment:
#   ONOS_CONNECTION: 'onos:8181'
#  volumes:
#   - "../docker/config/netcfg.json:/data/onos-config.json"
#  networks:
#   authnet:
#  links:
#   - "onos:onos"

# freeradius-test:
#  image: "${REGISTRY}marcelmaatkamp/freeradius:${RADIUS_TAG:-latest}"
#  command: "radtest user password freeradius 0 SECRET"
#  networks:
#   authnet:
#    ipv4_address: 172.25.0.101

networks:
  authnet:
    driver: bridge
    ipam:
      config:
      - subnet: 172.25.0.0/24
